
- name: Create Application User
  ansible.builtin.user:
    name: roboshop

- name: Cleaning the old content
  ansible.builtin.file:
   path: /app
   state: absent

- name: Create a app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Unzip the catalogue app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes

