
#echo -e "\e[36m>>>>>>>>>>>>  Build ${component} Service   <<<<<<<<<<<<\e[0m"
#pip3.6 install -r requirements.txt &>>${log}
#func_exit_status
#
#func_systemd

- name: Payment Setup
  hosts: all
  become: true
  vars:
    component: payment
  tasks:
    - name: Build {{component}} Service
      ansible.builtin.yum:
        name: python36 gcc python3-devel
        state: installed
    - name: App Pre-requisite
      ansible.builtin.import_tasks: app-prerequisite.yml

    - name: Build {{component}} Service
      ansible.builtin.shell: pip3.6 install -r requirements.txt
      args:
        chdir: /app
