- name: Payment Setup
  hosts: all
  become: true
  vars:
    component: payment
  tasks:
    - name: Build {{component}} Service
      ansible.builtin.yum:
        name:
          - python36
          - gcc
          - python3-devel
        state: installed

    - name: App Pre-requisite
      ansible.builtin.import_tasks: app-prerequisite.yml

    - name: Install packages
      ansible.builtin.shell: pip3.6 install -r requirements.txt
      args:
        chdir: /app

    - name: Restart the payment service
      ansible.builtin.systemd:
        name: payment
        state: started
        enabled: true
