- name: RabbitMQ setup
  hosts: all
  become: true
  tasks:
    - name: Get the erlang repos
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: Get the Rabbitmq repos
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: Install rabbitmq-server
      ansible.builtin.yum:
        name: rabbitmq-server
        state: installed

    - name: Restart the service
      ansible.builtin.systemd:
        name: rabbitmq-server
        state: started
        enabled: true

    - name: Adding the user and setting the permissions
      ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"