- name: Redis setup
  hosts: all
  become: true
  tasks:
    - name: Download remi repo file
      ansible.builtin.yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: installed
        disable_gpg_check: true

    - name: Enable redis module
      ansible.builtin.shell: dnf module enable redis:remi-6.2 -y

    - name: Install redis
      ansible.builtin.yum:
        name: redis
        state: installed

    - name: Update Listen address in redis.conf
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Update Listen address in redis/redis.conf
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Restart the redis service
      ansible.builtin.systemd:
        name: redis
        enabled: true
        restarted: true


